#! /bin/bash

if [ ! -f $samplesheet ]; then
  echo 'Samplesheet not provided or does not exist. Please provide a samplesheet'
  exit
fi

samplesheet="$1"
mkdir -p results

# file to track the status of samples
echo "Sample  Tool  QC Status" > results/sample_status.tsv  # overwrite if previously ran


while IFS= read -r line; do
  sample=$(echo $line | cut -d , -f 1)
  r1=$(echo $line | cut -d , -f 2)
  r2=$(echo $line | cut -d , -f 3)
  echo "Processing $sample"

  mkdir -p "results/$sample"

  # verify the input files exist
  if [ ! -f "$r1" ]; then
    echo "File $r1 does not exist"
    exit
  fi

  if [ ! -f "$r2" ]; then
    echo "File $r2 does not exist"
    exit
  fi

  # read qc

  # perform assembly using shovill
  bash scripts/run_shovill $r1 $r2 $sample
  assembly=results/$sample/shovill/assembly/$sample.fa
  assembly_dir=results/$sample/shovill/assembly

  # run quast
  bash scripts/run_quast $assembly $sample

  # run CheckM
  bash scripts/run_checkm $assembly_dir $sample
  
done < $samplesheet


# check pass/fail samples and save them to a directory
mkdir -p results/passed_assemblies
samples=$(sed '1,1d' results/sample_status.tsv | cut -f 1 | uniq)
for sample in $samples; do
  fail_search=$(grep -w $sample results/sample_status.tsv | grep -w 'failed')
  if [ -z "$fail_search"]; then
    echo "$sample passed"
    ln -s $(PWD)/results/$sample/shovill/assembly/$sample.fa -t $(PWD)/results/passed_assemblies
  else
    echo "$sample failed"
  fi
done

# iterate through pass and get amr, virulence

# collect all pass for cg and make tree
