#!/usr/bin/env bash

source /opt/conda/etc/profile.d/conda.sh
conda activate amr

ASSEMBLY=$1        
SAMPLE=$2          

OUTPUT="results/$SAMPLE/amrfinderplus"
IDENT_MIN="${IDENT_MIN:-0.9}"
COV_MIN="${COV_MIN:-0.5}"
TRANSLATION_TABLE="${TRANSLATION_TABLE:-11}"
THREADS=$(nproc --all)

mkdir -p "$OUTPUT"

amrfinder \
  --nucleotide "$ASSEMBLY" \
  --output "$OUTPUT/${SAMPLE}.amrfinderplus.tsv" \
  --threads "$THREADS" \
  --ident_min "$IDENT_MIN" \
  --coverage_min "$COV_MIN" \
  --translation_table "$TRANSLATION_TABLE" \
  --plus \
  > "$OUTPUT/${SAMPLE}.amrfinderplus.log" 2>&1

echo "AMRFinderPlus complete. Results in ${OUTPUT}"