#!/usr/bin/env bash

source /opt/conda/etc/profile.d/conda.sh
conda activate bio

R1=$1
R2=$2
SAMPLE=$3

OUT_DIR="results/$SAMPLE/fastqc"
THREADS=$(nproc --all)

mkdir -p $OUT_DIR

fastqc --quiet --threads $THREADS --outdir $OUT_DIR $R1 $R2

echo "FastQC complete. Results in $OUT_DIR"
